import './globals.css'
import { Inter, Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ 
  subsets: [ 'latin' ],
  weight: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ]
})

export const metadata = {
  title: 'Next.JS App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <nav>
          <h1>Logo</h1>
          <ul>
            <li> <a href="#"> Home </a> </li>
            <li> <a href="#"> About </a> </li>
            <li> <a href="#"> Services </a> </li>
            <li> <a href="#"> Contact </a> </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
