import './globals.css'
import { Inter, Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ 
  subsets: [ 'latin' ],
  weight: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ]
})

export const metadata = {
  title: 'Next.JS App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
